### ISSUE TITLE
Check Virus Warning Pls.

### ISSUE THREAD

**Issue by kmscom** [xvim64/vim-text-viewer#1]
Dear XVIM developer(s),

Hi!
I downloaded the following latest VIM release and uncompressed it.
After uncompressing, my vaccine (Avira Antivirus Pro) detected the following virus warning.
Check it pls.

* https://github.com/xvim64/vim-text-viewer/releases/download/1.0.12/vimview-1.0.12-gvim-8.2.4306-x64.zip
from https://github.com/xvim64/vim-text-viewer/releases

* Virus warning - HEUR/AGEN.1207925
https://www.avira.com/en/support-threats-summary/7952?track=1

**Comment by xvim64** [comment]
// clean
https://www.virustotal.com/gui/file/0dd81741ae1e41b9a366ec6eb0590ed8934451dba19ab3afee6e16f0ecfd6f16?nocache=1
https://www.virustotal.com/gui/file/5453a2368afd816288533ef8ec3bc2ad75f5d56df52f48cca7cbfe25b74e4ae3

// avira detection
https://www.virustotal.com/gui/file/1f68612decdbabf227a4b3b5c8a862e776778d6fefbb7bf64c5592112d96cd56?nocache=1
https://www.virustotal.com/gui/file/927528c7acd20191ed4439d431867031ac612805ce716087c207cb36c314e0a4?nocache=1

// other detections
https://www.virustotal.com/gui/file/4f25d55311d775ef71b012e6f8d1f20b8e4447a95a771a39bf56b6ce7e1b115c?nocache=1
https://www.virustotal.com/gui/file/5562e0fabbcdf9a967d68258a12d886b7fba6fcef30ac7b30d8e0bd35ca9839d?nocache=1
https://www.virustotal.com/gui/file/a98874e020a41fe7022286a7bb128e0d6abac2e131208cd6ce154cd83976fbd5?nocache=1
https://www.virustotal.com/gui/file/73b2375c352d6f0036fc76467f072a4fa615f0c162c1128573e78da3d5abf1b9


Avira seems to detect the CreateProcessW() function as a suspicious action.

If you don't want to use vi.exe, VimView.exe, use the *.cmd batch file.

But the Command Prompt Window will appear before launching gvim.exe.

Or compile it yourself using Visual Studio.

These *.cmd batch files work the same as the VimView.exe and vi.exe. (See VimView.c and vi.c)

``` VimView.cmd
@echo off
pushd "%~dp0"
start vim82\gvim.exe -u config\_vimrc.txt %*
exit /b
```

``` vi.cmd
@echo off
pushd "%~dp0"
start vim82\gvim.exe -u config\_vimrc_vi.txt %*
exit /b
```

or

Copy '\~\\VimView\\config\\_vimrc.txt' to '\~\\VimView\\_vimrc', and execute gvim.exe directly.


ps. These below 2 files that are detected are in the github vim-win32 x64 official release.

https://github.com/vim/vim-win32-installer/releases/download/v8.2.4306/gvim_8.2.4306_x64.zip

// detectinos
https://www.virustotal.com/gui/file/5b8b190069042faa885e915c57d49f1e6ab3b8814b1e1eb112c5b9fd0fe4696f?nocache=1
https://www.virustotal.com/gui/file/7d3fe7e21562d28e26a3e2db1df19ca53dd2a182fc2e5f0f980556732f1e830a?nocache=1
